version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.4.0 
  aws-eks: circleci/aws-eks@1.1.0
  aws-cli: circleci/aws-cli@2.0.3

commands: 
  linux-install-aws:
    description: installs awscli v2 using pip
    steps:
      - run: 
          name: install aws cli
          command: |
            
            if (aws --version)
            then 
              export AWSV=$(aws --version | cut -d/ -f2 | cut -d. -f1)
              if  [ $(($AWSV>1)) ]
              then
                echo cli already installed
              else
                echo uninstalling old aws version now
                sudo rm -rf /usr/local/aws
                sudo rm /usr/local/bin/aws  
                echo installing new version now
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                ./aws/install
                aws --version
            fi 
            else  
              echo installing new version now
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
              aws --version
            fi
jobs:
  Lint:
    
    docker:
      - image: python:3.7.3-stretch
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install pylint
            pip install pylint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: Docker lint
          command: |
            . venv/bin/activate
            hadolint Dockerfile
      - run:
          name: pylint
          command: |
            . venv/bin/activate
            pylint app.py --errors-only


  docker-build-push:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - deploy:
          name: Push Docker image
          command: |
            DOCKERPATH="vtm1983/udacity-devops-capstone"
            docker build --tag=udacity-devops-capstone .
            docker login -u vtm1983 -p "$DOCKER_PASSWORD"
            docker image tag udacity-devops-capstone $DOCKERPATH:latest
            docker image push $DOCKERPATH
            docker image tag udacity-devops-capstone $DOCKERPATH:${CIRCLE_WORKFLOW_ID:0:7}
            docker image push $DOCKERPATH:${CIRCLE_WORKFLOW_ID:0:7}

  deploy-app-to-eks:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - run:
          name: Install ekstcl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version
            aws --version
            kubectl version --short --client
      - run:
          name: Create eks-cluster
          command: |     
            # eksctl create cluster \
            # --name capstone-project-eks \
            # --region us-west-2 \
            # --nodegroup-name worker-node \
            # --node-type t3.micro \
            # --nodes 2 \
            # --nodes-min 1 \
            # --nodes-max 2               
      - run:
          name: Deploy To eks-cluster
          command: |
            aws eks --region us-west-2 update-kubeconfig --name capstone-project-eks
            kubectl apply -f k8files/service.yml
            kubectl apply -f k8files/deploy.yml


  testing-cluster:
    executor: aws-eks/python3
    
    steps:
      - checkout
      - kubernetes/install-kubectl
      - aws-cli/setup
      - run:
          name: test-deployment
          command: |
            aws eks --region us-west-2 update-kubeconfig --name capstone-project-eks
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pod
            ./output.sh

  rolling-deployment:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install-kubectl
      - aws-cli/setup
      - run:
          command: |
            aws eks --region us-west-2 update-kubeconfig --name capstone-project-eks
            kubectl rollout restart deployment capstone-project
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pod
            ./output.sh

workflows:
  Default:
    jobs:
      - deploy-app-to-eks:
          context: 
            - docker-secrets
            - aws-cred