apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
  labels:
    app: capstone-project
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
    spec:
      containers:
        - name: capstone-project
          image: vtm1983/udacity-devops-capstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: default-port