apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-deploy
  labels:
    app: udacity-devops-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-devops-capstone
      version: v1
  template:
    metadata:
      labels:
        app: udacity-devops-capstone
        version: v1
    spec:
      containers:
        - name: capstone-project
          image: vtm1983/udacity-devops-capstone
          ports:
            - containerPort: 8080