apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer