apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-service
spec:
  selector:
    app: udacity-devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer