kind: Service
metadata:
  name: capstone-project
  labels:
    app: capstone-project 
spec:
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer